name: Deploy staging

on:
  push:
    branches:
      - staging

env:
  PRIVATE_KEY: ${{secrets.STAGING_PRIVATE_KEY}}
  USER: ${{secrets.STAGING_USER}}
  IP: ${{secrets.STAGING_IP}}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Set up environment
        run: |
          echo $PRIVATE_KEY > key
          echo TODO create .env
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          tar -C build -czf web.tar.gz .
          scp -i ./key web.tar.gz $USER@$IP:/tmp
          ssh -i ./key $USER@$IP sudo rm -rf /var/www/web/* && sudo tar -C /var/www/web -xzf /tmp/web.tar.gz
