name: Deploy staging

on:
  push:
    branches:
      - staging

env:
  PRIVATE_KEY: ${{secrets.STAGING_PRIVATE_KEY}}
  USER: ${{secrets.STAGING_USER}}
  IP: ${{secrets.STAGING_IP}}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Set up environment
        run: |
          mkdir -p ~/.ssh
          echo $PRIVATE_KEY > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $IP
          echo -n > .env.production
          echo REACT_APP_CHAIN_ID=97 >> .env.production
          echo REACT_APP_NODE_1=https://data-seed-prebsc-1-s1.binance.org:8545 >> .env.production
          echo REACT_APP_NODE_2=https://data-seed-prebsc-1-s2.binance.org:8545 >> .env.production
          echo REACT_APP_NODE_3=https://data-seed-prebsc-1-s3.binance.org:8545 >> .env.production
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          tar -C build -czf web.tar.gz .
          scp -i ~/.ssh/id_rsa web.tar.gz $USER@$IP:/tmp
          ssh -i ~/.ssh/id_rsa $USER@$IP sudo rm -rf /var/www/web/*
          ssh -i ~/.ssh/id_rsa $USER@$IP sudo tar -C /var/www/web -xzf /tmp/web.tar.gz
